version: "3.9"

# シングルノードで動かす
services:
  vespa-node:
    image: vespaengine/vespa:8.215.17
    container_name: vespa-node
    hostname: vespa-node
    ports:
      - "8080:8080"
      - "19071:19071"
  mysql:
    image: mysql:8.0.32
    ports:
      - 3306:3306
    volumes:
      - db-store:/var/lib/mysql
      - ./logs:/var/log/mysql
      - ./schema:/docker-entrypoint-initdb.d
    container_name: my-db
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true

  swagger-editor:
    image: swaggerapi/swagger-editor
    container_name: "swagger-editor"
    ports:
      - "8001:8080"

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "8002:8080"
    volumes:
      - ./search-api/openapi.yaml:/openapi.yaml
    environment:
      SWAGGER_JSON: /openapi.yaml

  swagger-api:
    image: stoplight/prism:3
    container_name: "swagger-presentation"
    ports:
      - "8003:4010"
    command: mock -h 0.0.0.0 /openapi.yaml
    volumes:
      - ./search-api/openapi.yaml:/openapi.yaml
volumes:
  db-store:
