version: "3.9"

# シングルノードで動かす
services:
  vespa-node:
    image: vespaengine/vespa:8.215.17
    container_name: vespa-node
    hostname: vespa-node
    ports:
      - "8080:8080"
      - "19071:19071"
  mysql:
    image: mysql:8.0.32
    ports:
      - 3306:3306
    volumes:
      - db-store:/var/lib/mysql
      - ./logs:/var/log/mysql
      - ./schema:/docker-entrypoint-initdb.d
    container_name: my-db
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
volumes:
  db-store:
